[pipeline]
name = "minimal"
desc = "Testing a minimal set of functionality"

[pipeline.userInput]
valueFor = [
    "VIDEO_IN",
    "DATABASE_FILE"
]



[[stage]]
name = "hello-world"

[stage.image]
name = "ubuntu" # ENTRYPOINT python3 detector.py
args = ["/bin/bash", "-c", "echo 'hello from a docker image that is executed somehwere, managed by nomad and coordinated by winslow' && sleep 1 && date; touch /resources/abc; touch /workspace/def ; ls -lah /resources && ls -lah /workspace && echo bye"]

[stage.requires.gpu]
vendor = "nvidia"


[[stage]]
name = "write-to-workspace-file"

[stage.image]
name = "ubuntu"
args = ["/bin/bash", "-c", "date | tee /workspace/date; sleep 2; date; sleep 2"]



[[stage]]
name = "print-env-variable"

[stage.image]
name = "ubuntu"
args = ["/bin/bash", "-c", "echo \"VIDEO_IN=$VIDEO_IN\"; echo \"DATABASE_FILE=$DATABASE_FILE\";sleep 3"]
