[pipelineDefinition]
name = "vehicle-tracking"
desc = "Detects all vehicles in a video and tracks them through the video"

[pipelineDefinition.userInput]
valueFor = [
    "VIDEO_IN",
    "DATABASE_FILE"
]



[[stageDefinition]]
name = "car-detection"
desc = "Detecting all vehicles on each single frame through an AI"

[stageDefinition.image]
name = "mecview.itd-services.de/detector" # ENTRYPOINT python3 detector.py
args = ["inference", "--gpus", "0,1,2,3", "-p", "$VIDEO_IN"]

[stageDefinition.requires.gpu]
count = 4
vendor = "nvidia"
support = ["cuda", "vulkan"] # hmm?

[stageDefinition.progress]
from-log = '([\w]): Progress update: ([\d]+\.[\d]+)%'




[[stageDefinition]]
name = "confirm-detection"
depends-on = ["car-detection"]

[stageDefinition.userInput]
confirmation = "Always" # Never|Once|Always
value-for = ["WHATEVER_PATH",  "PATH_TO_THE_GREAT_FILE"]



[[stageDefinition]]
name = "vehicletracker-smoothing"
depends-on = ["confirm-detection"]

[stageDefinition.image]
name = "mecview.itd-services.de/vehicletracker" # ENTRYPOINT java -Xmx40g -jar vehicletracker.jar -p cli
args = ["-f", "$DATABASE_FILE", "-b", "ParticleTrackerIOTracks", "-b", "SmoothTracks", "-b", "LaneDetector"]

[stageDefinition.requires]
ram = 40960

[stageDefinition.fail]
if-log-contains = ["0 records detected", "bus error"]
if-log-matches = ['[\d]+ errors']

[stageDefinition.warn]
if-log-contains = ["this should never happen"]

[stageDefinition.allow]
exit-codes = [202, 108, 105]

[stageDefinition.deny]
exit-codes = [0]




[[stageDefinition]]
name = "vehicletracker-movie"
depends-on = ["vehicletracker-smoothing"]

[stageDefinition.image]
name = "mecview.itd-services.de/vehicletracker" # ENTRYPOINT java -jar vehicletracker.jar -p cli
args = ["-f", "$DATABASE_FILE", "-b", "RenderVideo"]

[stageDefinition.env]
OUTPUT_DIR = "abc/def/"

[stageDefinition.highlight]
resources = ["TheMovie.mp4"]



[[stageDefinition]]
name  = "export-trajectories"
depends-on = ["vehicletracker-smoothing"]

[stageDefinition.image]
name = "mecview.itd-services.de/vehicletracker" # ENTRYPOINT java -jar vehicletracker.jar -p cli
args = ["-f", "$DATABASE_FILE", "-b", "ExportTracjectories"]

[stageDefinition.highlight]
resources = ["trajectories/*.csv"]

