name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - '**'
    tags:
      - '20**.*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short_sha.outputs.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 ${{ github.sha }})"


  test-component-server:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          mvn clean test verify
          mv application/target/site/jacoco coverage-report
          awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' coverage-report/jacoco.csv
        env:
          CI_COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}

  build-component-server:
    needs:
      - test-component-server
      - prepare
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sed -i "s/external__BUILD_DATE/$(date '+%Y-%m-%d %H:%M:%S')/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          sed -i "s/external__COMMIT_HASH_LONG/${{ github.sha }}/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          sed -i "s/external__COMMIT_HASH_SHORT/${{ needs.prepare.outputs.short_sha }}/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          mvn clean test verify package
          cp application/target/winslow*.jar .
          mv application/target/site/jacoco coverage-report
          awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' coverage-report/jacoco.csv
          mvn -pl .,api package
          cp api/target/winslow*.jar .
          (cd api; mvn typescript-generator:generate)
          cp api/target/typescript-generator/winslow-api.ts .
          ls -lah
        env:
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: winslow-${{ github.sha }}
          path: |
            winslow*.jar
            coverage-report
            winslow-api.ts
#
#  publish-component-server-on-artifact-share:
#    needs: build-component-server
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Publish
#        run: |
#          echo "Publishing artifacts..."
#          # Here, you would include commands to publish your artifacts, possibly using actions/upload-artifact or custom scripts for deployment to your servers.
#        env:
#          NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
#          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
#          CI_COMMIT_TAG: ${{ github.ref }}
#          # Set your environment variables as needed
