name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - '**'
    tags:
      - '20**.*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short_sha.outputs.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 ${{ github.sha }})"


  test-component-server:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      - uses: actions/checkout@v4
      - name: cache m2
        uses: actions/cache@v4
        with:
          path: /root/.m2
          key: pom.xml-${{ hashFiles('pom.xml') }}
      - name: Test
        run: |
          mvn clean test verify
          mv application/target/site/jacoco coverage-report
          awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' coverage-report/jacoco.csv
        env:
          CI_COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}

  build-component-server:
    needs:
      - prepare
      - test-component-server
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      - uses: actions/checkout@v4
      - name: cache m2
        uses: actions/cache/restore@v4
        with:
          path: /root/.m2
          key: pom.xml-${{ hashFiles('pom.xml') }}
      - name: Build
        run: |
          sed -i "s/external__BUILD_DATE/$(date '+%Y-%m-%d %H:%M:%S')/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          sed -i "s/external__COMMIT_HASH_LONG/${{ github.sha }}/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          sed -i "s/external__COMMIT_HASH_SHORT/${{ needs.prepare.outputs.short_sha }}/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          mvn clean verify package -DskipTests
          cp application/target/winslow*.jar .
          # mv application/target/site/jacoco coverage-report
          # awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' coverage-report/jacoco.csv
          mvn -pl .,api package
          cp api/target/winslow*.jar .
          ls -lah
        env:
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}
#      - name: Cache winslow-api.ts
#        uses: actions/cache@v4
#        with:
#          path:
#            winslow-api.ts
#          # The hash of the file is used as key, because when the file changes and the cache is still valid then no cache can be created
#          # and all steps that depend on the cache will use the old file
#          key:
#            winslow-api.ts-${{ hashFiles('winslow-api.ts') }}
#          # All dependent steps can use this restore key and will get the latest version of the file
#          restore-keys: |
#            winslow-api.ts-

  publish-component-server-on-artifact-share:
    needs:
      - build-component-server
      - prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: |
          - echo $WINSLOW_API_TS_URL
          - echo $WINSLOW_API_TS_URL_LATEST
          - echo $WINSLOW_API_TS_URL_TAGGED
          - export WINSLOW_API_TS_URL="$(eval echo $WINSLOW_API_TS_URL)"
          - export WINSLOW_API_TS_URL_LATEST="$(eval echo $WINSLOW_API_TS_URL_LATEST)"
          - export WINSLOW_API_TS_URL_TAGGED="$(eval echo $WINSLOW_API_TS_URL_TAGGED)"
          - echo $WINSLOW_API_TS_URL
          - echo $WINSLOW_API_TS_URL_LATEST
          - echo $WINSLOW_API_TS_URL_TAGGED
          - export ARCHIVE=winslow-api.ts
          - ls -lah $ARCHIVE
          - head -n 2 $ARCHIVE
          - curl -i -u "$NEXUS_LOGIN" --upload-file "$ARCHIVE" "$WINSLOW_API_TS_URL"
          - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then curl -i -u "$NEXUS_LOGIN" --upload-file $ARCHIVE "$WINSLOW_API_TS_URL_LATEST"; fi
          - if [ "$CI_COMMIT_TAG" != "" ]; then curl -i -u "$NEXUS_LOGIN" --upload-file $ARCHIVE "$WINSLOW_API_TS_URL_TAGGED"; fi
        env:
          WINSLOW_API_TS_URL: "$NEXUS_RAW_WINSLOW_URL/api/build/winslow-api_$CI_COMMIT_SHORT_SHA.ts"
          WINSLOW_API_TS_URL_LATEST: "$NEXUS_RAW_WINSLOW_URL/api/winslow-api.ts"
          WINSLOW_API_TS_URL_TAGGED: "$NEXUS_RAW_WINSLOW_URL/api/winslow-api.ts"
          NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
          CI_COMMIT_TAG: ${{ github.ref }}
          # Set your environment variables as needed


  #  deploy-component-server:
  #    needs:
  #      - job: build-component-server
  #        artifacts: true
  #    only:
  #      refs:
  #        - master
  #        - tags
  #        - /^20\d\d.[\d]+$/
  #    tags:
  #      - dockerbuilder
  #    script:
  #      - ls -lah .
  #      - export TAG="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME:-latest}}"
  #      - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
  #      - echo $TAG
  #      - docker build . -t $DOCKER_REGISTRY_WINSLOW/winslow/component-server:$TAG
  #      - docker login -u $DOCKER_REGISTRY_WINSLOW_USERNAME -p $DOCKER_REGISTRY_WINSLOW_PASSWORD $DOCKER_REGISTRY_WINSLOW
  #      - docker push $DOCKER_REGISTRY_WINSLOW/winslow/component-server:$TAG

  build-component-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: create winslow-api.ts
        run: |
          (cd api; mvn typescript-generator:generate)
          cp api/target/typescript-generator/winslow-api.ts ui-ng/src/app/api/winslow-api.ts
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build
        run: |
          cd ui-ng
          npm install
          file src/app/api/winslow-api.ts
          npm run build --prod --configuration=production --baseHref=/ --deployUrl=/
          mv dist/winslow-ui-ng ../winslow-ui-ng
#       - uses: actions/upload-artifact@v2
#         with:
#          name: winslow-ui-ng_${{ github.sha }}
#          path: winslow-ui-ng

#deploy-component-html:
#  needs:
#    - job: build-component-html
#      artifacts: true
#  only:
#    refs:
#      - master
#      - tags
#      - /^20\d\d.[\d]+$/
#  tags:
#    - dockerbuilder
#  script:
#    - mv winslow-ui-ng ui-ng/winslow-ui-ng
#    - cd ui-ng
#    - ls -lah .
#    - export TAG="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME:-latest}}"
#    - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
#    - echo $TAG
#    - docker build . -t $DOCKER_REGISTRY_WINSLOW/winslow/component-html:$TAG
#    - docker login -u $DOCKER_REGISTRY_WINSLOW_USERNAME -p $DOCKER_REGISTRY_WINSLOW_PASSWORD $DOCKER_REGISTRY_WINSLOW
#    - docker push $DOCKER_REGISTRY_WINSLOW/winslow/component-html:$TAG
#
#
#deploy-winslow-node:
#  needs:
#    - deploy-component-server
#    - deploy-component-html
#  only:
#    refs:
#      - master
#      - tags
#      - /^20\d\d.[\d]+$/
#  tags:
#    - dockerbuilder
#  script:
#    - export TAG="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME:-latest}}"
#    - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
#    - echo $TAG
#    - cd node
#    - docker pull nexus.itd-intern.de/winslow/component-html:$TAG
#    - docker pull nexus.itd-intern.de/winslow/component-server:$TAG
#    - docker build . -t $DOCKER_REGISTRY_WINSLOW/winslow/node:$TAG
#      --build-arg COMPONENT_HTML=nexus.itd-intern.de/winslow/component-html:$TAG
#      --build-arg COMPONENT_SERVER=nexus.itd-intern.de/winslow/component-server:$TAG
#    - docker login -u $DOCKER_REGISTRY_WINSLOW_USERNAME -p $DOCKER_REGISTRY_WINSLOW_PASSWORD $DOCKER_REGISTRY_WINSLOW
#    - docker push $DOCKER_REGISTRY_WINSLOW/winslow/node:$TAG
