name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - '**'
    tags:
      - '20**.*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short_sha.outputs.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 ${{ github.sha }})"


  test-component-server:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Test
        run: |
          mvn clean test verify
          # TODO: Add coverage report
        env:
          CI_COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}

  build-component-server:
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup 'Build.java' information
        run: |
          sed -i "s/external__BUILD_DATE/$(date '+%Y-%m-%d %H:%M:%S')/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          sed -i "s/external__COMMIT_HASH_LONG/${{ github.sha }}/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
          sed -i "s/external__COMMIT_HASH_SHORT/${{ needs.prepare.outputs.short_sha }}/g" api/src/main/java/de/itdesigners/winslow/api/Build.java
      - name: Build
        run: |
          mvn clean verify package -DskipTests
      - name: Prepare upload jar files
        run: |
          cp application/target/winslow*.jar .
          cp api/target/winslow*.jar .
      - name: Upload jar files
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: jar-files-${{ github.run_id }}
          path: |
            winslow*.jar
        env:
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.short_sha }}
    #      - name: Cache winslow-api.ts
    #        uses: actions/cache@v4
    #        with:
    #          path:
    #            winslow-api.ts
    #          # The hash of the file is used as key, because when the file changes and the cache is still valid then no cache can be created
    #          # and all steps that depend on the cache will use the old file
    #          key:
    #            winslow-api.ts-${{ hashFiles('winslow-api.ts') }}
    #          # All dependent steps can use this restore key and will get the latest version of the file
    #          restore-keys: |
    #            winslow-api.ts-

    #  publish-component-server-on-artifact-share:
    #    needs:
    #      - build-component-server
    #      - test-component-server
    #      - prepare
    #    runs-on: ubuntu-latest
    #    steps:
    #      - uses: actions/checkout@v4
    #      - name: Publish
    #        run: |
    #          - echo $WINSLOW_API_TS_URL
    #          - echo $WINSLOW_API_TS_URL_LATEST
    #          - echo $WINSLOW_API_TS_URL_TAGGED
    #          - export WINSLOW_API_TS_URL="$(eval echo $WINSLOW_API_TS_URL)"
    #          - export WINSLOW_API_TS_URL_LATEST="$(eval echo $WINSLOW_API_TS_URL_LATEST)"
    #          - export WINSLOW_API_TS_URL_TAGGED="$(eval echo $WINSLOW_API_TS_URL_TAGGED)"
    #          - echo $WINSLOW_API_TS_URL
    #          - echo $WINSLOW_API_TS_URL_LATEST
    #          - echo $WINSLOW_API_TS_URL_TAGGED
    #          - export ARCHIVE=winslow-api.ts
    #          - ls -lah $ARCHIVE
    #          - head -n 2 $ARCHIVE
    #          - curl -i -u "$NEXUS_LOGIN" --upload-file "$ARCHIVE" "$WINSLOW_API_TS_URL"
    #          - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then curl -i -u "$NEXUS_LOGIN" --upload-file $ARCHIVE "$WINSLOW_API_TS_URL_LATEST"; fi
    #          - if [ "$CI_COMMIT_TAG" != "" ]; then curl -i -u "$NEXUS_LOGIN" --upload-file $ARCHIVE "$WINSLOW_API_TS_URL_TAGGED"; fi
    #        env:
    #          WINSLOW_API_TS_URL: "$NEXUS_RAW_WINSLOW_URL/api/build/winslow-api_$CI_COMMIT_SHORT_SHA.ts"
    #          WINSLOW_API_TS_URL_LATEST: "$NEXUS_RAW_WINSLOW_URL/api/winslow-api.ts"
    #          WINSLOW_API_TS_URL_TAGGED: "$NEXUS_RAW_WINSLOW_URL/api/winslow-api.ts"
    #          NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
    #          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
    #          CI_COMMIT_TAG: ${{ github.ref }}
    #          # Set your environment variables as needed



  deploy-component-server:
    needs:
      - build-component-server
      - test-component-server
    if: github.ref == 'refs/heads/239-create-a-workflow-file-for-github' ||
      github.ref == 'master' ||
      github.ref == 'refs/tags/20**.*'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: jar-files-${{ github.run_id }}
          path: .
      - name: Publish
        run: |
          ls -lah .
          docker build .

  #- ls -lah .
  #- export TAG="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME:-latest}}"
  #- if [ "$TAG" == "master" ]; then export TAG="latest"; fi
  #- echo $TAG
  #- docker build . -t $DOCKER_REGISTRY_WINSLOW/winslow/component-server:$TAG
  #- docker login -u $DOCKER_REGISTRY_WINSLOW_USERNAME -p $DOCKER_REGISTRY_WINSLOW_PASSWORD $DOCKER_REGISTRY_WINSLOW
  #- docker push $DOCKER_REGISTRY_WINSLOW/winslow/component-server:$TAG

  build-component-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: create winslow-api.ts
        run: |
          cd api
          mvn compile typescript-generator:generate
          cd ..
      - name: copy winslow-api.ts to ui-ng
        run: |
          cp api/target/typescript-generator/winslow-api.ts ui-ng/src/app/api/winslow-api.ts
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ui-ng/package-lock.json
      - name: prepare build
        run: |
          cd ui-ng
          npm install
      - name: Build
        run: |
          cd ui-ng
          npm run build --prod --configuration=production --baseHref=/ --deployUrl=/
      - name: Prepare upload
        run: |
          cd ui-ng
          mv dist/winslow-ui-ng ../winslow-ui-ng
      - name: Upload winslow-ui-ng
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 9
          name: winslow-ui-ng_${{ github.run_id }}
          path: winslow-ui-ng



  #deployment-condition-component-server:
  #  needs:
  #    - build-component-server
  #    - test-component-server
  #    - build-component-html
  #  if: github.ref == 'refs/heads/239-create-a-workflow-file-for-github' ||
  #    github.ref == 'master' ||
  #    github.ref == 'refs/tags/20**.*'
  #  runs-on: ubuntu-latest
  #  steps:

  #    run: |
  #      exit 1

  deploy-component-html:
    runs-on: ubuntu-latest
    needs:
      - build-component-html
    if: github.ref == 'refs/heads/239-create-a-workflow-file-for-github' ||
      github.ref == 'master' ||
      github.ref == 'refs/tags/20**.*'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: winslow-ui-ng_${{ github.run_id }}
      - name: Publish
        run: |
          ls -alh
          mv winslow-ui-ng ui-ng/winslow-ui-ng
          cd ui-ng
          docker build .
    #           ls -lah .
    #           export TAG="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME:-latest}}"
    #           if [ "$TAG" == "master" ]; then export TAG="latest"; fi
    #           echo $TAG
    #           docker build . -t $DOCKER_REGISTRY_WINSLOW/winslow/component-html:$TAG
    #           docker login -u $DOCKER_REGISTRY_WINSLOW_USERNAME -p $DOCKER_REGISTRY_WINSLOW_PASSWORD $DOCKER_REGISTRY_WINSLOW
    #           docker push $DOCKER_REGISTRY_WINSLOW/winslow/component-html:$TAG
    #deploy-component-html:
    #  needs:
    #    - job: build-component-html
    #      artifacts: true
    #  only:
    #    refs:
    #      - master
    #      - tags
    #      - /^20\d\d.[\d]+$/
    #  tags:
    #    - dockerbuilder
    #  script:
    #    - mv winslow-ui-ng ui-ng/winslow-ui-ng
    #    - cd ui-ng
    #    - ls -lah .
    #    - export TAG="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME:-latest}}"
    #    - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
    #    - echo $TAG
    #    - docker build . -t $DOCKER_REGISTRY_WINSLOW/winslow/component-html:$TAG
    #    - docker login -u $DOCKER_REGISTRY_WINSLOW_USERNAME -p $DOCKER_REGISTRY_WINSLOW_PASSWORD $DOCKER_REGISTRY_WINSLOW
    #    - docker push $DOCKER_REGISTRY_WINSLOW/winslow/component-html:$TAG
    #
    #

  deploy-winslow-node:
    runs-on: ubuntu-latest
    needs:
      - deploy-component-server
      - deploy-component-html
    #      only:
    #        refs:
    #          - master
    #          - tags
    #          - /^20\d\d.[\d]+$/
    #      tags:
    #        - dockerbuilder
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: ls

#deploy-winslow-node:
#  needs:
#    - deploy-component-server
#    - deploy-component-html
#  only:
#    refs:
#      - master
#      - tags
#      - /^20\d\d.[\d]+$/
#  tags:
#    - dockerbuilder
#  script:
#    - export TAG="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME:-latest}}"
#    - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
#    - echo $TAG
#    - cd node
#    - docker pull nexus.itd-intern.de/winslow/component-html:$TAG
#    - docker pull nexus.itd-intern.de/winslow/component-server:$TAG
#    - docker build . -t $DOCKER_REGISTRY_WINSLOW/winslow/node:$TAG
#      --build-arg COMPONENT_HTML=nexus.itd-intern.de/winslow/component-html:$TAG
#      --build-arg COMPONENT_SERVER=nexus.itd-intern.de/winslow/component-server:$TAG
#    - docker login -u $DOCKER_REGISTRY_WINSLOW_USERNAME -p $DOCKER_REGISTRY_WINSLOW_PASSWORD $DOCKER_REGISTRY_WINSLOW
#    - docker push $DOCKER_REGISTRY_WINSLOW/winslow/node:$TAG
